project:
  type: website
  resources: 
    - resume.pdf

website:
  title: "Daniel Jenkins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto

